# Generated by Django 3.2.9 on 2021-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navbar_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_title', models.CharField(max_length=50)),
                ('nav_link', models.URLField(max_length=100)),
            ],
        ),
    ]
