# Generated by Django 3.2.9 on 2021-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_auto_20211130_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='background_hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(upload_to='')),
                ('background_title', models.CharField(max_length=100)),
                ('background_stitle', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=25)),
            ],
        ),
    ]
