# Generated by Django 3.2.9 on 2021-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_alter_background_hero_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_head', models.CharField(max_length=50)),
                ('service_image', models.ImageField(upload_to='services')),
                ('service_title', models.CharField(max_length=25)),
                ('service_description', models.CharField(max_length=250)),
            ],
        ),
    ]
