# Generated by Django 3.2.9 on 2021-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='why_metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_head', models.CharField(max_length=50)),
                ('why_content', models.CharField(max_length=500)),
            ],
        ),
    ]
