# Generated by Django 3.2.9 on 2021-12-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0007_why_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_head',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.CharField(max_length=1000),
        ),
    ]
