# Generated by Django 3.2.9 on 2021-12-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0012_alter_customer_review_reviewer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_head', models.CharField(max_length=50)),
                ('metro_address', models.CharField(max_length=100)),
                ('metro_phn', models.CharField(max_length=20)),
                ('copyright_details', models.CharField(max_length=50)),
                ('other_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='get_in_touch_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=50)),
                ('social_media_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
