# Generated by Django 3.2.9 on 2021-12-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0013_auto_20211207_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.FileField(upload_to=''),
        ),
    ]
